[package]
name = "isotopes"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "Variants of common types for enforcing invariance."
homepage = "https://github.com/thebrownfoxx/isotopes"
repository = "https://github.com/thebrownfoxx/isotopes"
readme = "README.md"

[dependencies]
